name: Build Java Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup Oracle JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 17
      - name: build JAR
        run: mvn clean install
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
